sscats = [
[4,'Soins eclat','https://citymall-para.ma/categorie/visage/soins-anti-age-anti-rides/soins-eclat/'],
[5,'Premières rides','https://citymall-para.ma/categorie/visage/soins-anti-age-anti-rides/premieres-rides/'],
[6,'Rides installées','https://citymall-para.ma/categorie/visage/soins-anti-age-anti-rides/rides-installees/'],
[7,'Rides marquées / perte de fermeté','https://citymall-para.ma/categorie/visage/soins-anti-age-anti-rides/rides-marquees-perte-de-fermete/'],
[9,'Démaquillants yeux','https://citymall-para.ma/categorie/visage/yeux-et-levres/demaquillants-yeux/'],
[10,'Soins Anti-poches et cernes','https://citymall-para.ma/categorie/visage/yeux-et-levres/soins-anti-poches-et-cernes/'],
[11,'Contour des yeux et lèvres','https://citymall-para.ma/categorie/visage/yeux-et-levres/contour-des-yeux-et-levres/'],
[12,'Soins cils et sourcils','https://citymall-para.ma/categorie/visage/yeux-et-levres/soins-cils-et-sourcils/'],
[13,'Sticks lèvres et Réparateurs','https://citymall-para.ma/categorie/visage/yeux-et-levres/sticks-levres-et-reparateurs/'],
[15,'Eau / Tonique / Lotion','https://citymall-para.ma/categorie/visage/demaquillants-nettoyants-visage/eau-tonique-lotion/'],
[16,'Lait / Mousse / Emulsion','https://citymall-para.ma/categorie/visage/demaquillants-nettoyants-visage/lait-mousse-emulsion/'],
[17,'Gel / Crème / Huile','https://citymall-para.ma/categorie/visage/demaquillants-nettoyants-visage/gel-creme-huile/'],
[18,'Cotons démaquillants / Lingettes et éponges','https://citymall-para.ma/categorie/visage/demaquillants-nettoyants-visage/cotons-demaquillants-lingettes-et-eponges/'],
[20,'Hydratants toutes peaux','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/hydratants-toutes-peaux/'],
[21,'Hydratants peaux normales à mixtes','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/hydratants-peaux-normales-a-mixtes/'],
[22,'Hydratants peaux sèches','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/hydratants-peaux-seches/'],
[23,'Hydratants peaux intolérantes','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/hydratants-peaux-intolerantes/'],
[24,'Hydratants peaux atopiques','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/hydratants-peaux-atopiques/'],
[25,'Soins teintés / bonne mine','https://citymall-para.ma/categorie/visage/soins-hydratants-et-nutrition/soins-teintes-bonne-mine/'],
[27,'Nettoyants / Purifiants','https://citymall-para.ma/categorie/visage/soins-peau-grasse-mixte-acne/nettoyants-purifiants/'],
[28,'Matifiants / Hydratants','https://citymall-para.ma/categorie/visage/soins-peau-grasse-mixte-acne/matifiants-hydratants/'],
[29,'Soins teintés','https://citymall-para.ma/categorie/visage/soins-peau-grasse-mixte-acne/soins-teintes/'],
[30,'Soins spécifiques','https://citymall-para.ma/categorie/visage/soins-peau-grasse-mixte-acne/soins-specifiques/'],
[32,'Masques visage','https://citymall-para.ma/categorie/visage/masques-visage/'],
[33,'Gommages et exfoliants visage','https://citymall-para.ma/categorie/visage/gommages-et-exfoliants-visage/'],
[34,'Eau thermales','https://citymall-para.ma/categorie/visage/eau-thermales/'],
[35,'Soins anti-rougeurs / peau sensible / squames','https://citymall-para.ma/categorie/visage/soins-anti-rougeurs-peau-sensible-squames/'],
[36,'Soins anti-taches & dépigmentants','https://citymall-para.ma/categorie/visage/soins-anti-taches-depigmentants/'],
[37,'Soins réparateurs / cicatrisants','https://citymall-para.ma/categorie/visage/soins-reparateurs-cicatrisants/'],
[38,'Outils & accessoires beauté','https://citymall-para.ma/categorie/visage/outils-accessoires-beaute/'],
[41,'Doux et Fréquent','https://citymall-para.ma/categorie/cheveux/shampooing/doux-et-frequent/'],
[42,'Antipelliculaire','https://citymall-para.ma/categorie/cheveux/shampooing/antipelliculaire/'],
[43,'Cheveux Gras','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-gras/'],
[44,'Cuir Chevelu Sensible','https://citymall-para.ma/categorie/cheveux/shampooing/cuir-chevelu-sensible/'],
[45,'Cheveux Secs','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-secs/'],
[46,'Cheveux Frisés et Crépus','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-frises-et-crepus/'],
[47,'Cheveux Colorés','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-colores/'],
[48,'Cheveux Longs et Fins','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-longs-et-fins/'],
[49,'Cheveux Cassants / Dévitalisés','https://citymall-para.ma/categorie/cheveux/shampooing/cheveux-cassants-devitalises/'],
[50,'Reflets et Brillance','https://citymall-para.ma/categorie/cheveux/shampooing/reflets-et-brillance/'],
[52,'Aprés-shampooing','https://citymall-para.ma/categorie/cheveux/apres-shampooing-soin-des-cheveux/apres-shampooing/'],
[53,'Soins Défrisant et Lissant','https://citymall-para.ma/categorie/cheveux/apres-shampooing-soin-des-cheveux/soins-defrisant-et-lissant/'],
[54,'Masques / Baumes / Huiles Capillaires','https://citymall-para.ma/categorie/cheveux/apres-shampooing-soin-des-cheveux/masques-baumes-huiles-capillaires/'],
[55,'Sérums et Ampoules Capillaires','https://citymall-para.ma/categorie/cheveux/apres-shampooing-soin-des-cheveux/serums-et-ampoules-capillaires/'],
[56,'Soins Spray Cappilaires','https://citymall-para.ma/categorie/cheveux/apres-shampooing-soin-des-cheveux/soins-spray-cappilaires/'],
[58,'Shampooing Anti-Chute','https://citymall-para.ma/categorie/cheveux/soins-anti-chute/shampooing-anti-chute/'],
[59,'Ampoules et Lotions Anti-Chute','https://citymall-para.ma/categorie/cheveux/soins-anti-chute/ampoules-et-lotions-anti-chute/'],
[61,'Shampooing Anti-poux','https://citymall-para.ma/categorie/cheveux/soins-anti-poux/shampooing-anti-poux/'],
[62,'Lotions Anti-poux','https://citymall-para.ma/categorie/cheveux/soins-anti-poux/lotions-anti-poux/'],
[63,'Accessoires Anti-poux','https://citymall-para.ma/categorie/cheveux/soins-anti-poux/accessoires-anti-poux/'],
[65,'Brossage – Accessoires','https://citymall-para.ma/categorie/cheveux/appareils-outils-de-coiffure/brossage-accessoires/'],
[66,'Fixation, Gel','https://citymall-para.ma/categorie/cheveux/appareils-outils-de-coiffure/fixation-gel/'],
[67,'Mousse, Crème','https://citymall-para.ma/categorie/cheveux/appareils-outils-de-coiffure/mousse-creme/'],
[68,'Sèche cheveux','https://citymall-para.ma/categorie/cheveux/appareils-outils-de-coiffure/seche-cheveux/'],
[69,'Tondeuses','https://citymall-para.ma/categorie/cheveux/appareils-outils-de-coiffure/tondeuses/'],
[71,'Colorations','https://citymall-para.ma/categorie/cheveux/colorations/'],
[72,'Soins à la kératine','https://citymall-para.ma/categorie/cheveux/soins-a-la-keratine/'],
[75,'Soins Hydratation','https://citymall-para.ma/categorie/corps/hydratation-nutrition-corps/soins-hydratation/'],
[76,'Soins Hydratation Anti-âge','https://citymall-para.ma/categorie/corps/hydratation-nutrition-corps/soins-hydratation-anti-age/'],
[77,'Soins Hydratation Peaux Séches et Atopiques','https://citymall-para.ma/categorie/corps/hydratation-nutrition-corps/soins-hydratation-peaux-seches-et-atopiques/'],
[78,'Soins Hydratation Teintés / Bonne mine','https://citymall-para.ma/categorie/corps/hydratation-nutrition-corps/soins-hydratation-teintes-bonne-mine/'],
[80,'Mains Séches et Abîmées','https://citymall-para.ma/categorie/corps/soins-des-mains/mains-seches-et-abimees/'],
[81,'Soins Anti-tache / Anti-âge Mains','https://citymall-para.ma/categorie/corps/soins-des-mains/soins-anti-tache-anti-age-mains/'],
[83,'Soins des ongles','https://citymall-para.ma/categorie/corps/manucure/soins-des-ongles/'],
[84,'Vernis à ongles','https://citymall-para.ma/categorie/corps/manucure/vernis-a-ongles/'],
[85,'Dissolvant','https://citymall-para.ma/categorie/corps/manucure/dissolvant/'],
[87,'Pieds Secs et Abîmées','https://citymall-para.ma/categorie/corps/soins-pieds/pieds-secs-et-abimees/'],
[88,'Pieds Fatigués et échauffés','https://citymall-para.ma/categorie/corps/soins-pieds/pieds-fatigues-et-echauffes/'],
[89,'Pansements Pieds et Coussinets','https://citymall-para.ma/categorie/corps/soins-pieds/pansements-pieds-et-coussinets/'],
[90,'Pédicure','https://citymall-para.ma/categorie/corps/soins-pieds/pedicure/'],
[92,'Crème et Mousse Dépilatoire','https://citymall-para.ma/categorie/corps/epilation/creme-et-mousse-depilatoire/'],
[93,'Cire et Bandes Dépilatoires','https://citymall-para.ma/categorie/corps/epilation/cire-et-bandes-depilatoires/'],
[95,'Lait corps éclaircissant','https://citymall-para.ma/categorie/corps/lait-corps-eclaircissant/'],
[96,'Gommage et exfoliant corps','https://citymall-para.ma/categorie/corps/gommage-et-exfoliant-corps/'],
[97,'Jambes lourds','https://citymall-para.ma/categorie/corps/jambes-lourds/'],
[98,'Soins buste et seins','https://citymall-para.ma/categorie/corps/soins-buste-et-seins/'],
[99,'Accessoires manucure et pédicure','https://citymall-para.ma/categorie/corps/accessoires-manucure-et-pedicure/'],
[100,'Articulations','https://citymall-para.ma/categorie/corps/articulations/'],
[101,'Massage et détente','https://citymall-para.ma/categorie/corps/massage-et-detente/'],
[104,'Dentifrices Protection Caries','https://citymall-para.ma/categorie/dentaire/dentifrices/dentifrices-protection-caries/'],
[105,'Dentifrices Gencives Sensibles','https://citymall-para.ma/categorie/dentaire/dentifrices/dentifrices-gencives-sensibles/'],
[106,'Dentifrices Blanchissants','https://citymall-para.ma/categorie/dentaire/dentifrices/dentifrices-blanchissants/'],
[107,'Dentifrices Enfants','https://citymall-para.ma/categorie/dentaire/dentifrices/dentifrices-enfants/'],
[108,'Dentifrices Orthodontiques','https://citymall-para.ma/categorie/dentaire/dentifrices/dentifrices-orthodontiques/'],
[110,'Brosses à Dents manuelles','https://citymall-para.ma/categorie/dentaire/brosse-a-dents/brosses-a-dents-manuelles/'],
[111,'Brosses à Dents Électriques','https://citymall-para.ma/categorie/dentaire/brosse-a-dents/brosses-a-dents-electriques/'],
[112,'Brosses à Dents Enfants','https://citymall-para.ma/categorie/dentaire/brosse-a-dents/brosses-a-dents-enfants/'],
[113,'Brosses à Dents Spécialisées','https://citymall-para.ma/categorie/dentaire/brosse-a-dents/brosses-a-dents-specialisees/'],
[115,'Haleine fraîche','https://citymall-para.ma/categorie/dentaire/haleine-fraiche/'],
[116,'Bain de bouche','https://citymall-para.ma/categorie/dentaire/bain-de-bouche/'],
[117,'Soin gencive','https://citymall-para.ma/categorie/dentaire/soin-gencive/'],
[118,'Fils dentaires','https://citymall-para.ma/categorie/dentaire/fils-dentaires/'],
[119,'Appareils dentaires','https://citymall-para.ma/categorie/dentaire/appareils-dentaires/'],
[120,'Accessoires dentaires','https://citymall-para.ma/categorie/dentaire/accessoires-dentaires/'],
[123,'Gel douche / Savon liquide / Gommage','https://citymall-para.ma/categorie/hygiene/douche-bain/gel-douche-savon-liquide-gommage/'],
[124,'Gel douche et savon peaux atopiques','https://citymall-para.ma/categorie/hygiene/douche-bain/gel-douche-et-savon-peaux-atopiques/'],
[125,'Huiles lavantes','https://citymall-para.ma/categorie/hygiene/douche-bain/huiles-lavantes/'],
[126,'Savon et pain','https://citymall-para.ma/categorie/hygiene/douche-bain/savon-et-pain/'],
[127,'Bain (moussant / huile / sels / soins','https://citymall-para.ma/categorie/hygiene/douche-bain/bain-moussant-huile-sels-soins/'],
[129,'Déodorants et Anti-transpirants','https://citymall-para.ma/categorie/hygiene/deodorants/deodorants-et-anti-transpirants/'],
[130,'Déodorants fraicheur','https://citymall-para.ma/categorie/hygiene/deodorants/deodorants-fraicheur/'],
[131,'Stick / Spray / Roll-on','https://citymall-para.ma/categorie/hygiene/deodorants/stick-spray-roll-on/'],
[133,'Hygiène nasale','https://citymall-para.ma/categorie/hygiene/nez-et-oreilles/hygiene-nasale/'],
[134,'Nettoyage auriculaire','https://citymall-para.ma/categorie/hygiene/nez-et-oreilles/nettoyage-auriculaire/'],
[135,'Protection auditive','https://citymall-para.ma/categorie/hygiene/nez-et-oreilles/protection-auditive/'],
[136,'Sérum physiologique','https://citymall-para.ma/categorie/hygiene/nez-et-oreilles/serum-physiologique/'],
[137,'Ronflement','https://citymall-para.ma/categorie/hygiene/nez-et-oreilles/ronflement/'],
[139,'Toilette intime','https://citymall-para.ma/categorie/hygiene/hygiene-intime/toilette-intime/'],
[140,'Lingettes Intimes','https://citymall-para.ma/categorie/hygiene/hygiene-intime/lingettes-intimes/'],
[141,'Tampons','https://citymall-para.ma/categorie/hygiene/hygiene-intime/tampons/'],
[142,'Serviettes hygiéniques / Slips jetables','https://citymall-para.ma/categorie/hygiene/hygiene-intime/serviettes-hygieniques-slips-jetables/'],
[143,'Soins intimes','https://citymall-para.ma/categorie/hygiene/hygiene-intime/soins-intimes/'],
[144,'Protections incontinence et couches adultes','https://citymall-para.ma/categorie/hygiene/hygiene-intime/protections-incontinence-et-couches-adultes/'],
[146,'Gel lubrifiants','https://citymall-para.ma/categorie/hygiene/sexualite/gel-lubrifiants/'],
[147,'Tests de grocesse et d’ovulation','https://citymall-para.ma/categorie/hygiene/sexualite/tests-de-grocesse-et-dovulation/'],
[149,'Hammam & SPA','https://citymall-para.ma/categorie/hygiene/hammam-spa/'],
[150,'Spray & solutions antiseptiques','https://citymall-para.ma/categorie/hygiene/spray-solutions-antiseptiques/'],
[153,'Crème invisible','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-invisible/'],
[154,'Crème toucher sec','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-toucher-sec/'],
[155,'Crème toucher sec teintée','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-toucher-sec-teintee/'],
[156,'Crème teintée','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-teintee/'],
[157,'Crème fluide','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-fluide/'],
[158,'Lait et huiles solaires','https://citymall-para.ma/categorie/solaire/cremes-solaires/lait-et-huiles-solaires/'],
[159,'Crème fondante','https://citymall-para.ma/categorie/solaire/cremes-solaires/creme-fondante/'],
[160,'Brune et aerosol solaire','https://citymall-para.ma/categorie/solaire/cremes-solaires/brune-et-aerosol-solaire/'],
[162,'Crème Moussante','https://citymall-para.ma/categorie/solaire/creme-moussante/'],
[163,'Stick Lèvres Solaire','https://citymall-para.ma/categorie/solaire/stick-levres-solaire/'],
[164,'Autobronzants','https://citymall-para.ma/categorie/solaire/autobronzants/'],
[165,'Soins Après-Soleil','https://citymall-para.ma/categorie/solaire/soins-apres-soleil/'],
[166,' Émulsion','https://citymall-para.ma/categorie/solaire/emulsion/'],
[169,'Bain et toilette','https://citymall-para.ma/categorie/bebe-maman/hygiene-bebe/bain-et-toilette/'],
[170,'Lingettes Intimes','https://citymall-para.ma/categorie/hygiene/hygiene-intime/lingettes-intimes/'],
[171,'Couches bébé et Change','https://citymall-para.ma/categorie/bebe-maman/hygiene-bebe/couches-bebe-et-change/'],
[172,'Mouche bébé et hygiène nasale','https://citymall-para.ma/categorie/bebe-maman/hygiene-bebe/mouche-bebe-et-hygiene-nasale/'],
[174,'Biberons et tasses','https://citymall-para.ma/categorie/bebe-maman/puericulture/biberons-et-tasses/'],
[175,'Tétines','https://citymall-para.ma/categorie/bebe-maman/puericulture/tetines/'],
[176,'Sucettes Attaches-sucettes','https://citymall-para.ma/categorie/bebe-maman/puericulture/sucettes-attaches-sucettes/'],
[177,'Apprentissage repas','https://citymall-para.ma/categorie/bebe-maman/puericulture/apprentissage-repas/'],
[178,'Matériel','https://citymall-para.ma/categorie/bebe-maman/puericulture/materiel/'],
[180,'Soins Visage','https://citymall-para.ma/categorie/bebe-maman/soins-visage/'],
[181,'Soins Corps','https://citymall-para.ma/categorie/bebe-maman/soins-corps/'],
[182,'Tests De Grossesse Et D\'Ovulation','https://citymall-para.ma/categorie/bebe-maman/tests-de-grossesse-et-dovulation/'],
[183,'Alimentation Infantile','https://citymall-para.ma/categorie/bebe-maman/alimentation-infantile/'],
[184,'Allaitement Et Stérilisation','https://citymall-para.ma/categorie/bebe-maman/allaitement-et-sterilisation/'],
[185,'Eaux Parfumées Et Coffrets','https://citymall-para.ma/categorie/bebe-maman/eaux-parfumees-et-coffrets/'],
[186,'Soins Des Vergetures','https://citymall-para.ma/categorie/bebe-maman/soins-des-vergetures/'],
[187,'Complèments Alimentaires Grossesse','https://citymall-para.ma/categorie/bebe-maman/complements-alimentaires-grossesse/'],
[190,'Thermomètre','https://citymall-para.ma/categorie/sante/materiel-paramedical/thermometre/'],
[191,'Tensiomètre','https://citymall-para.ma/categorie/sante/materiel-paramedical/tensiometre/'],
[192,'Lecteur de glycémie et bandettes','https://citymall-para.ma/categorie/sante/materiel-paramedical/lecteur-de-glycemie-et-bandettes/'],
[194,'Matériel consommable','https://citymall-para.ma/categorie/sante/materiel-paramedical/materiel-consommable/'],
[195,'Pansements','https://citymall-para.ma/categorie/sante/pansements/'],
[196,'Rhume Soins Respiratoires Gorge','https://citymall-para.ma/categorie/sante/rhume-soins-respiratoires-gorge/'],
[197,'Mal Des Transports','https://citymall-para.ma/categorie/sante/mal-des-transports/'],
[198,'Crèmes Musculaires Sports','https://citymall-para.ma/categorie/sante/cremes-musculaires-sports/'],
[199,'Anti-Verrues','https://citymall-para.ma/categorie/sante/anti-verrues/'],
[200,'Anti-Moustiques','https://citymall-para.ma/categorie/sante/anti-moustiques/'],
[203,'Mousses / Gels / Crèmes à raser','https://citymall-para.ma/categorie/homme/rasage/mousses-gels-cremes-a-raser/'],
[204,'Après-rasage','https://citymall-para.ma/categorie/homme/rasage/apres-rasage/'],
[205,'Barbe et moustache','https://citymall-para.ma/categorie/homme/rasage/barbe-et-moustache/'],
[206,'Rasoirs','https://citymall-para.ma/categorie/homme/rasage/rasoirs/'],
[207,'Accessoires','https://citymall-para.ma/categorie/homme/rasage/accessoires/'],
[209,'Soins Hydratants','https://citymall-para.ma/categorie/homme/soins/soins-hydratants/'],
[210,'Anti-age et Anti-fatigue','https://citymall-para.ma/categorie/homme/soins/anti-age-et-anti-fatigue/'],
[212,'Performance physique','https://citymall-para.ma/categorie/homme/performance-physique/'],
[213,'Produit sexuel','https://citymall-para.ma/categorie/homme/produit-sexuel/'],
[214,'Hygiène','https://citymall-para.ma/categorie/homme/hygiene-homme-homme/'],
[217,'Comprimés et gélules','https://citymall-para.ma/categorie/complement-alimentaires/vitamines-et-forme/comprimes-et-gelules/'],
[218,'Ampoules / Sirop / Jus / Pastilles','https://citymall-para.ma/categorie/complement-alimentaires/vitamines-et-forme/ampoules-sirop-jus-pastilles/'],
[219,'Sachets et Poudre','https://citymall-para.ma/categorie/complement-alimentaires/vitamines-et-forme/sachets-et-poudre/'],
[221,'COMPLÈMENTS ANTI-ÂGE','https://citymall-para.ma/categorie/complement-alimentaires/complements-anti-age/'],
[222,'COMPLÈMENTS CHEVEUX ET ONGLES','https://citymall-para.ma/categorie/complement-alimentaires/complements-cheveux-et-ongles/'],
[223,'BIEN-ÊTRE, EQUILIBRE ÉMOTIONNEL, DÉPRIME','https://citymall-para.ma/categorie/complement-alimentaires/bien-etre-equilibre-emotionnel-deprime/'],
[224,'TRANSIT / DIGESTION / ELIMINATION','https://citymall-para.ma/categorie/complement-alimentaires/transit-digestion-elimination/'],
[225,'MÉNOPAUSE','https://citymall-para.ma/categorie/complement-alimentaires/menopause/'],
[226,'GYNÉCOLOGIE / TROUBLE URINAIRES','https://citymall-para.ma/categorie/complement-alimentaires/gynecologie-trouble-urinaires/'],
[227,'MÉMOIRE ET CONCENTRATION','https://citymall-para.ma/categorie/complement-alimentaires/memoire-et-concentration/'],
[228,'CIRCULATION, COEUR','https://citymall-para.ma/categorie/complement-alimentaires/circulation-coeur/'],
[229,'ARTICULATIONS ET GRAMPE','https://citymall-para.ma/categorie/complement-alimentaires/articulations-et-grampe/'],
[230,'SOMMEIL -DÉTENTE','https://citymall-para.ma/categorie/complement-alimentaires/sommeil-detente/'],
[231,'COMPLÈMENTS ALIMENTAIRES NATURELS','https://citymall-para.ma/categorie/complement-alimentaires/complements-alimentaires-naturels/'],
[232,'COMPLÉMENTS ALIMENTAIRES ENFANT','https://citymall-para.ma/categorie/complement-alimentaires/complements-alimentaires-enfant/'],
[233,'COMPLÈMENTS ALIMENTAIRES SÉNIOR','https://citymall-para.ma/categorie/complement-alimentaires/complements-alimentaires-senior/'],
[234,'SPÉCIAL SPORT','https://citymall-para.ma/categorie/complement-alimentaires/special-sport/'],
[235,'OPHTALMOLOGIE','https://citymall-para.ma/categorie/complement-alimentaires/ophtalmologie/'],
[236,'TROUBLES URINAIRES MASCULINS','https://citymall-para.ma/categorie/complement-alimentaires/troubles-urinaires-masculins/'],
[237,'DÉFENSES IMMUNITAIRES','https://citymall-para.ma/categorie/complement-alimentaires/defenses-immunitaires/'],
[238,'CONFISERIE','https://citymall-para.ma/categorie/complement-alimentaires/confiserie/'],
[241,'Rouge à lèvres / Gloss / Repulpant','https://citymall-para.ma/categorie/visage/maquillage/rouge-a-levres-gloss-repulpant/'],
[242,'Mascara','https://citymall-para.ma/categorie/visage/maquillage/mascara/'],
[243,'Crayon à yeux / Eye Liner','https://citymall-para.ma/categorie/visage/maquillage/crayon-a-yeux-eye-liner/'],
[244,'Crayon sourcils','https://citymall-para.ma/categorie/visage/maquillage/crayon-sourcils/'],
[245,'Fard à paupières','https://citymall-para.ma/categorie/visage/maquillage/fard-a-paupieres/'],
[246,'Fond de teint fluide','https://citymall-para.ma/categorie/visage/maquillage/fond-de-teint-fluide/'],
[247,'Poudre teint','https://citymall-para.ma/categorie/visage/maquillage/poudre-teint/'],
[248,'Correcteurs de teint','https://citymall-para.ma/categorie/visage/maquillage/correcteurs-de-teint/'],
[249,'Accessoires Maquillage','https://citymall-para.ma/categorie/visage/maquillage/accessoires-maquillage/'],

]